---
- name: Check disk space
  ansible.builtin.shell: df -h / | awk 'NR==2{print $5}' | tr -d '%'
  register: root_fs_usage
 
- name: Check running services
  ansible.builtin.service_facts:
 
- name: Validate services
  ansible.builtin.assert:
    that: item in services
    fail_msg: "Service {{ item }} is not running"
  loop: "{{ required_services }}"
 
- name: Check CPU utilization
  ansible.builtin.shell: |
    echo "CPU: $(top -bn1 | grep 'Cpu(s)' | sed 's/.*, *\([0-9.]*\)%* id.*/\1/' | awk '{print 100 - $1}')%"
  register: cpu_usage
 
- name: Check memory usage
  ansible.builtin.shell: |
    free | awk '/Mem/{printf "%.2f", $3/$2*100}'
  register: mem_usage
 
- name: Fail if thresholds exceeded
  ansible.builtin.fail:
      msg: |
        System checks failed:
        - Disk usage: {{ root_fs_usage.stdout }}%
        - CPU usage: {{ cpu_usage.stdout }}
        - Memory usage: {{ mem_usage.stdout }}%
  when: >
      root_fs_usage.stdout|int >= (100 - thresholds.disk_space) or
      cpu_usage.stdout|float >= thresholds.cpu_usage or
      mem_usage.stdout|float >= thresholds.memory_usage