---
# Threshold configurations
thresholds:
  disk_space: 15    # 15% minimum free
  cpu_usage: 90     # 90% max
  memory_usage: 85  # 85% max
 
# Required services
required_services:
  - sshd
  - chronyd
  - rsyslog
  - sssd
 
# Patch configuration
yum_clean_cmd: "yum clean all"
yum_update_cmd: "yum update -y --security"